theme: jekyll-theme-cayman
title: AutoConvert Greeklish Permalinks
description: Convert Greek characters to Latin on all your WordPress website's permalinks instantly.
show_downloads: true
google_analytics: UA-79194198-5