name: Build and Tag
on:
  push:
    branches:
      - master

jobs:
  wordpress:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm i
          npm run build
      - name: Setup
        run: 'echo "VERSION=$(grep -Po "Version: *[0-9\\.]+" auto-gr-permalinks.php | grep -Po "[0-9\\.]+")" >> $GITHUB_ENV'
      - name: Tag
        run: |
          echo "Releasing version $VERSION ..."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "v$VERSION"
          git push --tags
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
