name: PHPUnit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    name: ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set PHP version
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: phpunit-polyfills

      - name: Update dependencies
        run: composer update -W

      - name: PHPUnit Test
        run: ./vendor/bin/phpunit
